# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    -   id: black
        types: []
        files: ^.*.pyi?$  # format .py and .pyi files
        exclude: ^.*_pb2.pyi$
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-pyi,flake8-bugbear]
        types: []
        files: ^.*.pyi?$  # format .py and .pyi files
-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
    -   id: isort
